"""add walk verification fields

Revision ID: 3309e25ac4e1
Revises: c4130b7ae55d
Create Date: 2026-09-13 00:06:07.663303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3309e25ac4e1'
down_revision: Union[str, None] = 'c4130b7ae55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('flagged_for_review', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('walks', sa.Column('flag_reason', sa.String(length=500), nullable=True))
    op.add_column('walks', sa.Column('distance_meters', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_walks_flagged_for_review'), 'walks', ['flagged_for_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walks_flagged_for_review'), table_name='walks')
    op.drop_column('walks', 'distance_meters')
    op.drop_column('walks', 'flag_reason')
    op.drop_column('walks', 'flagged_for_review')
    # ### end Alembic commands ###
