"""add payments table

Revision ID: 4cbb49e4f0a4
Revises: de4ffe8d5a39
Create Date: 2026-09-12 23:17:09.220634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbb49e4f0a4'
down_revision: Union[str, None] = 'de4ffe8d5a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('walker_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'aprobado', 'rechazado', 'reembolsado', 'cancelado', name='payment_status'), nullable=False),
    sa.Column('mp_preference_id', sa.String(length=120), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=120), nullable=True),
    sa.Column('mp_status_detail', sa.String(length=120), nullable=True),
    sa.Column('init_point', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_mp_payment_id'), 'payments', ['mp_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_mp_preference_id'), 'payments', ['mp_preference_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_walk_id'), 'payments', ['walk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_walk_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_mp_preference_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_mp_payment_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
