"""add reviews table

Revision ID: ba346198b237
Revises: e1dd79eab1fd
Create Date: 2026-09-16 23:23:05.511876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba346198b237'
down_revision: Union[str, None] = 'e1dd79eab1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('walker_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['walker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walk_id', name='uq_reviews_walk_id')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_owner_id'), 'reviews', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reviews_walk_id'), 'reviews', ['walk_id'], unique=False)
    op.create_index(op.f('ix_reviews_walker_id'), 'reviews', ['walker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_walker_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_walk_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_owner_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
