"""add escrow fields to payments

Revision ID: c4130b7ae55d
Revises: 4cbb49e4f0a4
Create Date: 2026-09-12 23:56:24.385081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4130b7ae55d'
down_revision: Union[str, None] = '4cbb49e4f0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_release_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('confirmed_by_owner_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('dispute_opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('dispute_reason', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('released_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payments_payment_release_deadline'), 'payments', ['payment_release_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_release_deadline'), table_name='payments')
    op.drop_column('payments', 'released_at')
    op.drop_column('payments', 'dispute_reason')
    op.drop_column('payments', 'dispute_opened_at')
    op.drop_column('payments', 'confirmed_by_owner_at')
    op.drop_column('payments', 'payment_release_deadline')
    # ### end Alembic commands ###
