"""add walk_pets many-to-many

Revision ID: e1dd79eab1fd
Revises: 2cbc9e53c675
Create Date: 2026-09-13 00:43:24.150462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dd79eab1fd'
down_revision: Union[str, None] = '2cbc9e53c675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walk_id', 'pet_id', name='uq_walk_pets_walk_pet')
    )
    op.create_index(op.f('ix_walk_pets_pet_id'), 'walk_pets', ['pet_id'], unique=False)
    op.create_index(op.f('ix_walk_pets_walk_id'), 'walk_pets', ['walk_id'], unique=False)
    op.execute("""
        INSERT INTO walk_pets (walk_id, pet_id, created_at)
        SELECT id, pet_id, now()
        FROM walks
        WHERE pet_id IS NOT NULL
    """)
    op.drop_index('ix_walks_pet_id', table_name='walks')
    op.drop_constraint('walks_pet_id_fkey', 'walks', type_='foreignkey')
    op.drop_column('walks', 'pet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('walks_pet_id_fkey', 'walks', 'pets', ['pet_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_walks_pet_id', 'walks', ['pet_id'], unique=False)
    op.drop_index(op.f('ix_walk_pets_walk_id'), table_name='walk_pets')
    op.drop_index(op.f('ix_walk_pets_pet_id'), table_name='walk_pets')
    op.drop_table('walk_pets')
    # ### end Alembic commands ###
